### ISSUE TITLE
AttributeError: module 'selfcord' has no attribute 'Bot'

### ISSUE THREAD

**Issue by Vile-Seven** [QwertyL0L/rule34-selfbot#2]
File "C:\Users\a\Downloads\rule34-selfbot-main\main.py", line 57, in <module>
    bot = selfcord.Bot(prefixes="?")
          ^^^^^^^^^^^^
AttributeError: module 'selfcord' has no attribute 'Bot'

**Comment by QwertyL0L** [comment]
did u try to update the library???

also if you have any other issues then contact me on discord (wextraaa or qwertyl0l).

**Comment by QwertyL0L** [comment]
did you ever fix it?

**Comment by FeltMacaroon389** [comment]
I have the same issue

**Comment by QwertyL0L** [comment]
@FeltMacaroon389 add me on discord so i can help: wextraaa

**Comment by dragonGRaf** [comment]
when running run2.bat
`[2024-07-29 22:41:52] [INFO    ] discord.client: Logging in using static token.
[2024-07-29 22:41:53] [INFO    ] discord.http: Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36, build number 313344.
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 994, in static_login
    data = await self.get_me()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 838, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main2.py", line 183, in <module>
    bot.run(TOKEN)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 938, in run
    asyncio.run(runner())
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 927, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 857, in start
    await self.login(token)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 698, in login
    data = await state.http.static_login(token.strip())
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 998, in static_login
    raise LoginFailure('Improper token has been passed') from exc
discord.errors.LoginFailure: Improper token has been passed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000028FEE6C8280>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000028FEE6C8280>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Press any key to continue . . .`
